name: Bump JavaScript SDK Dependency

on:
  repository_dispatch:
    types: [bump-js-dependency]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Update JS dependency version
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          sed -i 's/"@mostly-good-metrics\/javascript": "[^"]*"/"@mostly-good-metrics\/javascript": "^'"$VERSION"'"/' package.json

      - name: Install to sync lockfile
        run: npm install --ignore-scripts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump @mostly-good-metrics/javascript to ^${{ github.event.client_payload.version }}"
          branch: bump-js-sdk-${{ github.event.client_payload.version }}
          title: "Bump JavaScript SDK to ${{ github.event.client_payload.version }}"
          body: "Updates @mostly-good-metrics/javascript dependency to ^${{ github.event.client_payload.version }}"
